import { describe, expect, it } from 'vitest';
import { composePRTitleAndBody } from './pr-composer.js';

describe('composePRTitleAndBody', () => {
  it('formats a short task description into title and body', () => {
    const { title, body } = composePRTitleAndBody(
      'Fix the login bug',
      'run-abc',
      ['src/auth.ts', 'src/login.ts'],
      true,
    );
    expect(title).toBe('repo-pilot: Fix the login bug');
    expect(body).toContain('Fix the login bug');
    expect(body).toContain('src/auth.ts');
    expect(body).toContain('src/login.ts');
    expect(body).toContain('Generated by RepoPilot — run run-abc');
    expect(body).toContain('Tests passed');
  });

  it('truncates title to 60 chars with ellipsis when task description is too long', () => {
    const longDescription =
      'This is a very long task description that exceeds sixty characters by quite a bit';
    const { title } = composePRTitleAndBody(longDescription, 'run-1', [], true);
    // "repo-pilot: " is 12 chars; first line capped at 60 chars
    const prefix = 'repo-pilot: ';
    const taskPart = title.slice(prefix.length);
    expect(taskPart.length).toBeLessThanOrEqual(63); // 60 chars + "…"
    expect(title.endsWith('…')).toBe(true);
  });

  it('includes test failure status in body when tests did not pass', () => {
    const { body } = composePRTitleAndBody('Add feature', 'run-2', ['src/feature.ts'], false);
    expect(body).toContain('Tests failed');
    expect(body).not.toContain('Tests passed');
  });

  it('includes footer with run ID', () => {
    const { body } = composePRTitleAndBody('task', 'my-run-id-999', [], true);
    expect(body).toContain('Generated by RepoPilot — run my-run-id-999');
  });

  it('handles empty changed files list gracefully', () => {
    const { body } = composePRTitleAndBody('task', 'run-3', [], true);
    // Should not crash; body is still formed
    expect(typeof body).toBe('string');
    expect(body.length).toBeGreaterThan(0);
  });

  it('uses only the first line of a multi-line task description for the title', () => {
    const multiLine = 'First line of task\nSecond line should not appear in title';
    const { title } = composePRTitleAndBody(multiLine, 'run-4', [], true);
    expect(title).toContain('First line');
    expect(title).not.toContain('Second line');
  });
});
