// D1-7: Pure function — no I/O, no side effects.
// Composes a deterministic PR title and body from task metadata.

/**
 * Compose a PR title and body for a RepoPilot-generated pull request.
 *
 * @param taskDescription - The original task entered by the user
 * @param runId           - The agent run ID (included in the footer)
 * @param changedFiles    - List of file paths modified in this run
 * @param testsPassed     - Whether the test run exited with code 0
 */
export function composePRTitleAndBody(
  taskDescription: string,
  runId: string,
  changedFiles: string[],
  testsPassed: boolean,
): { title: string; body: string } {
  // Use only the first line for the title — multi-line descriptions have details below
  const firstLine = taskDescription.split('\n')[0].trim();

  const MAX_TASK_CHARS = 60;
  const taskPart =
    firstLine.length > MAX_TASK_CHARS
      ? `${firstLine.slice(0, MAX_TASK_CHARS)}…`
      : firstLine;

  const title = `repo-pilot: ${taskPart}`;

  // Build a structured body with task description, files, test status, and footer
  const filesList =
    changedFiles.length > 0
      ? changedFiles.map((f) => `- \`${f}\``).join('\n')
      : '_No files recorded._';

  const testStatus = testsPassed ? '✅ Tests passed' : '❌ Tests failed';

  const body = [
    '## Task',
    '',
    taskDescription,
    '',
    '## Changed Files',
    '',
    filesList,
    '',
    '## Test Status',
    '',
    testStatus,
    '',
    '---',
    '',
    `Generated by RepoPilot — run ${runId}`,
  ].join('\n');

  return { title, body };
}
